### ISSUE TITLE
Migrate tests.sh to Makefile

### ISSUE THREAD

**Issue by avara1986** [python-microservices/microservices-scaffold#199]
Migrate tests.sh
```
#!/bin/sh
coverage erase
tox
coverage combine
coverage report -m
coverage html
pylint project/* > pylintReport.txt
```
to a Makefile, in example:

```
linter:
    pylint project/* > pylintReport.txt
test: 
    export CONFIGMAP_FILE=tests/config-tests.yml
    pytest
coverage: 
    coverage erase
    pytest ...
    coverage combine
```

**Comment by eftakhairul** [comment]
Hi, I am interested to work on this.

**Comment by avara1986** [comment]
Thank you @eftakhairul! ^^ Don't forget to register in https://hacktoberfest.digitalocean.com/ :+1: 

I assign to you the issue, is it ok?

Thanks again!

**Comment by eftakhairul** [comment]
@avara1986  Let me know that is what you looking for..

**Comment by avara1986** [comment]
Your PR is perfect @eftakhairul :heart: 

@scratchmex Your PR is very good too, but @eftakhairul tell me first to do the Issue #204. I'm going to merge #204 first but your PR is valid because you update the docs too.

Are you both agree with this resolution @eftakhairul and @scratchmex?

Thanks!

**Comment by eftakhairul** [comment]
I am okay.

**Comment by eftakhairul** [comment]
Good point. I updated doc as well.

**Comment by scratchmex** [comment]
I'm okay but now my PR is useless...
